CLEAR
CLOSE ALL
CLEAR ALL
RELEASE ALL
SET LOCK ON
SET MULTILOCKS ON
SET REFRESH TO 0
SET EXCLUSIVE OFF
SET REPROCESS TO 5 SECONDS
SET TALK OFF
SET UNIQUE OFF
SET NEAR OFF
SET ESCAPE OFF
SET STATUS ON
SET STATUS BAR ON
SET SAFETY OFF
SET NOTIFY OFF
SET DEBUG ON
SET EXACT OFF
SET DELETED ON
SET CONFIRM ON
SET DATE ITALIAN
SET CENTURY ON
SET CLOCK STATUS
SET HOURS TO 24
SET SEPARATOR TO ","
SET POINT TO "."
SET CPDIALOG OFF
SET NULLDISPLAY TO "0"
MPRINTNAME = SET("Printer", 2)
SET PRINTER TO &MPRINTNAME
CLOSE DATABASES
CLOSE ALL
CLEAR ALL
ON ERROR DO ERRHANDLER WITH  ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )
ON ERROR
PUBLIC DEFAICON
PUBLIC DIRCURR
PUBLIC GDATAX, GDTEMP, xtanggal
PUBLIC OXMENU, _AKSESOKE, _MULAI, _USERS, _PASWD, _TYPEUSER, _USERID
PUBLIC GICON, GHAND, GBGROUND, _ASEARCHING, GTITLE, GFOOTTITLE
PUBLIC GRND1, GRND2, GITALFORMAT
PUBLIC _ASEARCHING
PUBLIC GKOPN
PUBLIC GEXCEL
PUBLIC TGLNOW, DEFACONNECT, DEFANOMISMK, DEFAICON
PUBLIC DEFAUSERID, DEFAHAKMENU
PUBLIC DEFAHAKANGG, DEFAHAKSIMP, DEFAHAKPINJ, DEFAHAKKAS, DEFAHAKAKT, DEFAHAKCOL, DEFAHAKUSER, DEFAHAKSET
PUBLIC DEFAHAKREPT, DEFAAUTOBERKAS
PUBLIC DEFANAMA, DEFAALAMAT, DEFAKOTA, DEFAPHONE, DEFAID, DEFAPIMPINAN, DEFAJABATAN, DEFAPENGADILAN, DEFAKANTOR
PUBLIC DEFAIDUSER, DEFABATASKAS, DEFAIDGROUP
PUBLIC DEFAMASUK, DEFADBFSMS, TGLLAPORAN
PUBLIC DEFAREGASET, DEFAREGKANTOR, DEFAREGTGLJT, DEFAREGSTAT
PUBLIC DEFATGLKAS, DEFAMODELNRC, DEFAKETERANGAN, DEFATANGGAL, DEFAJUDUL
PUBLIC CSQL
PUBLIC xdrop1,xdrop2,xdrop3,xd1,xd2,xd3,xlunas1,xlunas2,xlunas3,xl1,xl2,xl3,xmswk,xkswk
PUBLIC xkol2,xnomkol2,xkol3,xnomkol3,xkol4,xnomkol4,xkol1,xnomkol1,xsurplusjln, xnomsmb

STORE '222222' TO DEFAHAKMENU, DEFAHAKREPT
STORE '0000000000' TO DEFAHAKANGG, DEFAHAKSIMP, DEFAHAKPINJ, DEFAHAKKAS, DEFAHAKAKT, DEFAHAKCOL, DEFAHAKUSER, DEFAHAKSET
DEFATGLKAS = DATE()
DEFAAUTOBERKAS = 'T'
DEFAMASUK = .F.
PUBLIC OODBC
OODBC = 0
IF  .NOT. ((SYSMETRIC(1)>=800) .AND. (SYSMETRIC(2)>=600))
	_SCREEN.VISIBLE = .F.
	MESSAGEBOX('Resolusi Harus 800×600', 48, 'Error!')
	_SCREEN.VISIBLE = .T.
	CANCEL
ENDIF
_SCREEN.VISIBLE = .F.
STORE 1 TO GNX
MDIR = ''
DO WHILE LEN(SYS(16, GNX))<>0
	MDIR = JUSTPATH(SYS(16, GNX))
	STORE GNX+1 TO GNX
ENDDO

MDIR=STRTRAN(MDIR, '\PROGS', '')

SET DEFAULT TO (MDIR)
SET PROCEDURE TO .\progs\pros, .\progs\pros_proses, .\progs\pros_menu, .\progs\pros1, .\progs\pros2, .\progs\pros_krd, .\progs\pros_simp, .\progs\buatini
SET PATH TO .\data;.\etmp\.;.\excel;.\form;.\image;,.\progs;.\report,.\vcx
SET CLASSLIB TO .\vcx\vfxoffce, .\vcx\mylib, .\vcx\myclassbutton, .\vcx\mybacaini
DIRCURR = MDIR
LOSERVER = READINI2("CONECTION", "SERVER", "", "TERRA.INI")
LONMDB = READINI2("CONECTION", "DATABASED", "", "TERRA.INI")
LODBUNAME = READINI2("CONECTION", "USER", "", "TERRA.INI")
LODBPWD = READINI2("CONECTION", "PASSWORD", "", "TERRA.INI")
LOPORT = READINI2("CONECTION", "PORT", "", "TERRA.INI")
DEFADBFSMS = READINI2("CONECTION", "SMSGATEWAY", "", "TERRA.INI")
GICON = ".\image\terra.ico"
GTITLE = READINI2("IMAGE", "TITLE", "title"+"defaiduser", "TERRA.INI")
GHAND = READINI2("IMAGE", "CURSOR", "", "TERRA.INI")
GBGROUND = READINI2("IMAGE", "BACKGROUND", "", "TERRA.INI")
GIMAGEKOP = READINI2("IMAGE", "KOPIMAGE", "", "TERRA.INI")
GFOOTTITLE = READINI2("IMAGE", "FOOT", "", "TERRA.INI")
DEFAKANTOR = READINI2("USERPROFIL", "IDKANTOR", "", "TERRA.INI")
DEFAIDUSER = READINI2("USERPROFIL", "IDPENGGUNA", "", "TERRA.INI")
DEFAICON = GICON
PUBLIC LCCON
LCCON = "DRIVER={MySQL ODBC 5.1 Driver};DESC=;DATABASE="+LONMDB+";SERVER="+LOSERVER+";UID="+LODBUNAME+";PASSWORD="+LODBPWD+";PORT="+LOPORT+";OPTION=;STMT=;"
*LCCON = "DRIVER={MariaDB ODBC 2.0 Driver};DESC=;DATABASE="+LONMDB+";SERVER="+LOSERVER+";UID="+LODBUNAME+";PASSWORD="+LODBPWD+";PORT=3306;OPTION=;STMT=;"

*MESSAgEbox(LCCON)
DEFACONNECT = LCCON
OODBC = SQLSTRINGCONNECT(DEFACONNECT) 
CSQL = "select COUNT(nama) as jml from user"
LCEK = SQLEXEC(OODBC, CSQL, "SMT")

IF LCEK<1
	MESSAGEBOX("Mohon dicek kembali file config.ini x", 64, "")
	RETURN
ELSE
	MJML = VAL(JML)
	USE
	IF MJML=0
		DEFAHAKUSER = '11111111'
	ENDIF
ENDIF
CSQL = "select * from batastanggal where kantor='"+DEFAKANTOR+"'"
LCEK = SQLEXEC(OODBC, CSQL, "smt")
IF TGLUPDATE<DATE()
	CSQL = "update batastanggal set tglakhir='"+SQLDATE(DATE())+"' where kantor='"+DEFAKANTOR+"'"
	LCEK = SQLEXEC(OODBC, CSQL)
ENDIF
*MIDMB = ID_MATHERBOARD()
DO DECLAREAPIS
*CEKVERSIDBF()
cekadadatabased()
STORE .F. TO GL2, INV2, AP2, CO2, AR2, UT2, GSITE
_USERS = ""
_PASWD = ""
_TYPEUSER = ""
_AKSESOKE = .F.
_MULAI = .F.
_ASEARCHING = ""
IF _MULAI=.F.
   _MULAI = .T.
  IF _MULAI=.T.
	 OXMENU = CREATEOBJECT('xFormsSet')
	 OXMENU.SHOW
	 DO FORM frm_login
	 IF DEFAHAKMENU='111111'
*!*		    tutup guntur 5 januari
*!*		    CEKJURNALPUBLIC()
		IF .F.
		   IF LEFT(DEFAREGKANTOR, 1)<>'8'
			  DO FORM reg_habis WITH 1
		   ENDIF
	 	   IF DEFAREGSTAT='2' .AND. (DEFAREGTGLJT+90)-TGLNOW<7
			  DO FORM reg_habis WITH 2
	   	   ENDIF
		   IF DEFAREGSTAT='3' .AND. DEFAREGTGLJT-TGLNOW<-30
			  DO FORM reg_habis WITH 3
		   ENDIF
		ENDIF
		CSQL = "select MAX(tglproses) as tgl from log_proses"
		LCEK = SQLEXEC(OODBC, CSQL, "SMT")
		MTGL = TGL
		USE
		
*!*			tutup 5 januari guntur
*!*			IF MTGL<TGLNOW
*!*			   DO FORM proses_harian2 WITH 0
*!*			ENDIF
	ENDIF
	READ EVENTS
  ELSE
	CLOSE DATABASES
	CLOSE ALL
	CLEAR ALL
	CLEAR EVENTS
   ENDIF
ENDIF
ENDPROC
**
DEFINE CLASS xformsSet AS formset
   AUTORELEASE = .T.
   WINDOWTYPE = 0
   MAINFORMCLOSE = .F.
   ADD OBJECT XMFORM AS MAINFORM
ENDDEFINE
**
DEFINE CLASS mainform AS FORM
   AUTOCENTER = .T.
   BORDERSTYLE = 0
   CAPTION = GTITLE
   CLOSABLE = .T.
   DESKTOP = .T.
   ICON = GICON
   HEIGHT = SYSMETRIC(2)-25
   MAXBUTTON = .T. 
   MDIFORM = .T.
   SHOWWINDOW = 2
   SHOWTIPS = .T.
   WIDTH = SYSMETRIC(1)
   WINDOWTYPE = 1
   WINDOWSTATE = 2
   BACKCOLOR = RGB(12, 124, 14)
   ADD OBJECT BACKGROUND AS IMAGE WITH BORDERSTYLE = 0, TOP = 0, LEFT = 0, WIDTH = SYSMETRIC(1), HEIGHT = SYSMETRIC(2), STRETCH = 2, PICTURE = GBGROUND, VISIBLE = IIF(FILE(GBGROUND), .T., .F.)
   ADD OBJECT SHAPE0 AS IMAGE WITH BORDERSTYLE = 0, TOP = 0, LEFT = 0, WIDTH = SYSMETRIC(1), HEIGHT = 140, PICTURE = "", STRETCH = 1, VISIBLE = .F.
   ADD OBJECT SHAPE_BAWAH AS SHAPE WITH BORDERSTYLE = 0, BACKCOLOR = RGB(128, 128, 0), TOP = SYSMETRIC(2)-65, LEFT = 0, WIDTH = SYSMETRIC(1), HEIGHT = 65
  
   **
   PROCEDURE init
      THISFORM.ADDPROPERTY("posx")
      THISFORM.ADDPROPERTY("posy")
      MAIN_MENU()
   ENDPROC
   **

   PROCEDURE background.rightClick
      THISFORM.RIGHTMENU()
   ENDPROC

   **
   PROCEDURE rightClick
      THISFORM.RIGHTMENU()
   ENDPROC
   **
   PROCEDURE rightmenu
      POSX = THISFORM.POSX
      POSY = THISFORM.POSY
      MPICT = ''
      DEFINE POPUP MYMENU FROM POSY/15, POSX/5 FONT "Times New Roman", 12 SHADOW
	  DEFINE BAR 1 OF MYMENU PROMPT "Ubah Tampilan Display Background          "
	  DEFINE BAR 2 OF MYMENU PROMPT "Ubah Tampilan Display Kop "
	  ON SELECTION BAR 1 OF MYMENU DO FORM GET_IMAGE WITH GBGROUND TO MPICT 
	  ON SELECTION BAR 2 OF MYMENU RETURN 
	  ACTIVATE POPUP MYMENU
	  IF  .NOT. EMPTY(MPICT)
	     GBGROUND = MPICT
	     THISFORM.TAMPILAWAL()
	  ENDIF
   ENDPROC
   **
	PROCEDURE background.mousemove
	   LPARAMETERS NBUTTON, NSHIFT, NXCOORD, NYCOORD
	   THISFORM.POSX = NXCOORD
	   THISFORM.POSY = NYCOORD
	ENDPROC
	**
	PROCEDURE mousemove
	   LPARAMETERS NBUTTON, NSHIFT, NXCOORD, NYCOORD
	   THISFORM.POSX = NXCOORD
	   THISFORM.POSY = NYCOORD
	ENDPROC
	**
	PROCEDURE tampilawal
		IF  .NOT. EMPTY(GBGROUND) .AND. FILE(GBGROUND)
		   THISFORM.BACKGROUND.PICTURE = GBGROUND
		   THISFORM.BACKGROUND.VISIBLE = .T.
		ELSE
		   THISFORM.BACKGROUND.VISIBLE = .F.
		ENDIF
		THISFORM.SHAPE_BAWAH.VISIBLE = .F.
		IF EMPTY(GIMAGEKOP)
		   THISFORM.SHAPE0.VISIBLE = .F.
		ELSE
		   THISFORM.SHAPE0.VISIBLE = .T.
		ENDIF
	ENDPROC
	**
	PROCEDURE Load
	   _SCREEN.VISIBLE = .F.
	ENDPROC
	**
	PROCEDURE destroy
	   THISFORMSET.MAINFORMCLOSE = .T.
	   CLOSE TABLE ALL
	   RELEASE MENU EXTENDED XMFORM
	   CLEAR EVENTS
	ENDPROC
**
ENDDEFINE
