* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
*  FileName READINI2.PRG <-- This file create by UnFoxAll
* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-


 PARAMETER PRMPARENTSECTION , PRMCHILDSECTION , PRMDEFAULTVALUE , PRMFILEINI
 DECLARE INTEGER GetPrivateProfileString IN Win32API AS GetPrivStr STRING , STRING ,  ;
      STRING , STRING @ , INTEGER , STRING 
 LOCAL FILEHANDLER , RETURNVALUE
 WINDINIPATH = 'C:\WINDOWS\' + PRMFILEINI
 IF FILE(WINDINIPATH)
 FILEHANDLER = FOPEN(WINDINIPATH,0)
 PRMFILEINILOC = 'C:\WINDOWS\' + PRMFILEINI
 ELSE 
 IF FILE(PRMFILEINI)
 FILEHANDLER = FOPEN(PRMFILEINI,0)
 PRMFILEINILOC = CURDIR() + PRMFILEINI
 ELSE 
 RETURNVALUE = PRMDEFAULTVALUE
 RETURN RETURNVALUE
 ENDIF 
 ENDIF 
 IF FILEHANDLER < 0
 WAIT WINDOW NOWAIT 'Gagal akses INI File.'
 = FCLOSE(FILEHANDLER)
 RETURNVALUE = PRMDEFAULTVALUE
 RETURN RETURNVALUE
 ELSE 
 = FCLOSE(FILEHANDLER)
 ENDIF 
 LOCAL LCBUFFER
 LCBUFFER = SPACE(500) + CHR(0)
 = GETPRIVSTR(PRMPARENTSECTION,PRMCHILDSECTION,PRMDEFAULTVALUE,@LCBUFFER,LEN(LCBUFFER),PRMFILEINILOC)
 LCBUFFER = ALLTRIM(STRTRAN(LCBUFFER,CHR(0),''))
 RETURN LCBUFFER
*
